#============================================================================
# ??JobStore
#============================================================================
# JobDataMaps????String?????false
org.quartz.jobStore.useProperties=false

# ???????QRTZ_
org.quartz.jobStore.tablePrefix = QRTZ_

# ??????
org.quartz.jobStore.isClustered = true

# ????????????? ms
org.quartz.jobStore.clusterCheckinInterval = 5000

# ?????true????????Quartz ????JDBC?????setTransactionIsolation?Connection.TRANSACTION_READ_COMMITTED??
org.quartz.jobStore.txIsolationLevelReadCommitted = true

# ?????????????
org.quartz.jobStore.class = org.quartz.impl.jdbcjobstore.JobStoreTX

# ?????????org.quartz.impl.jdbcjobstore.StdJDBCDelegate??????????
org.quartz.jobStore.driverDelegateClass = org.quartz.impl.jdbcjobstore.StdJDBCDelegate

#============================================================================
# Scheduler ???????
#============================================================================
# ????? ??????????????????
org.quartz.scheduler.instanceName = ClusterQuartz
# ID??????? ???????
org.quartz.scheduler.instanceId= AUTO

#============================================================================
# ??ThreadPool
#============================================================================
# ????????????SimpleThreadPool??????????????
org.quartz.threadPool.class=org.quartz.simpl.SimpleThreadPool

# ???????????1-100??????????????
org.quartz.threadPool.threadCount = 5

# ????????(???Thread.MIN_PRIORITY??1??Thread.MAX_PRIORITY???10??????int ?????Thread.NORM_PRIORITY?5??)
org.quartz.threadPool.threadPriority = 5