job:
  cron:
    myJob: "0/5 * * * * ?"

spring:
  datasource:
      url: jdbc:postgresql://localhost:5432/my_quartz
      username: postgres
      password: 123456
      hikari:
        minimum-idle: 5
        maximum-pool-size: 10
        idle-timeout: 10000
        connection-timeout: 30000
        max-lifetime: 600000
        pool-name: my-quartz
  jpa:
      show-sql: true
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
          ddl-auto: none